apiVersion: v1
kind: Pod
metadata:
  name: flask-redis
  labels:
    app: flask
spec:
  containers:
  - name: app
    image: clarusway/flask-redis
    ports:
    - containerPort: 5000
  - name: redis
    image: redis:alpine
    ports:
    - containerPort: 6379
---
apiVersion: v1
kind: Service   
metadata:
  name: flask-redis-svc
spec:
  type: NodePort 
  ports:
  - port: 5000 
    targetPort: 5000
    nodePort: 30002
  selector:
    app: flask