AWSTemplateFormatVersion: 2010-09-09
Description: |
  CloudFormation template for a static https website with CloudFront and Route 53 domain.
  
Parameters:

  pKittensDomainName:
    Description: Full subdomain for kittens website
    Type: String
    Default: mykittens.awsdevopscloud.com

  pHostedZoneId:
    Description: Hosted Zone ID
    Type: AWS::Route53::HostedZone::Id

Resources:

  rKittensBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref pKittensDomainName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: index.html
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - BucketKeyEnabled: true
            ServerSideEncryptionByDefault: 
                SSEAlgorithm: AES256

  rKittensBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref rKittensBucket
      PolicyDocument: 
        Id: PublicReadPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Join [ '', [ !GetAtt rKittensBucket.Arn, '/*' ] ]

  rDomainCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties: 
      DomainName: !Ref pKittensDomainName
      ValidationMethod: DNS
      DomainValidationOptions: 
        - DomainName: !Ref pKittensDomainName
          HostedZoneId: !Ref pHostedZoneId

  rCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: CloudFront distribution for kittens carousel
        Origins:
          - Id: KittensOrigin
            DomainName: !Select [2, !Split ["/", !GetAtt rKittensBucket.WebsiteURL]]
            CustomOriginConfig: 
              OriginProtocolPolicy: http-only
        DefaultRootObject: index.html
        Aliases:
          - !Ref pKittensDomainName
        ViewerCertificate: 
          AcmCertificateArn: !Ref rDomainCertificate
          MinimumProtocolVersion: TLSv1.2_2019
          SslSupportMethod: sni-only
        DefaultCacheBehavior: 
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods: 
            - GET
            - HEAD
          Compress: True
          ViewerProtocolPolicy: redirect-to-https
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          TargetOriginId: KittensOrigin
        HttpVersion: http2
        PriceClass: PriceClass_100

  rRecordSet:
    Type: AWS::Route53::RecordSet
    Properties: 
      AliasTarget: 
        DNSName: !GetAtt rCloudFrontDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2
      HostedZoneId: !Ref pHostedZoneId
      Name: !Ref pKittensDomainName
      Type: A
  
Outputs:

  CloudFrontURL:
    Description: URL to reach cloudfront distributions
    Value: !Join [ '', [ 'https://', !GetAtt rCloudFrontDistribution.DomainName ] ]

  S3WebsiteURL:
    Description: URL to reach s3 website directly
    Value: !GetAtt rKittensBucket.WebsiteURL

  KittensDomainName:
    Description: Domain name for recordset
    Value: !Join [ '', [ 'https://', !Ref rRecordSet ] ]